### ISSUE TITLE
snakePipes envInfo: AttributeError: 'NoneType' object has no attribute 'encode'

### ISSUE THREAD

**Issue by sunta3iouxos** [kilpert/snakemake_workflows#992]
I run the following and get a weird issue.
```bash
snakePipes envInfo
Traceback (most recent call last):
  File "/scratch/tgeorgom/mamba/snakepipes_devel/bin/snakePipes", line 441, in <module>
    main(sys.argv[1:])
  File "/scratch/tgeorgom/mamba/snakepipes_devel/bin/snakePipes", line 427, in main
    envInfo()
  File "/scratch/tgeorgom/mamba/snakepipes_devel/bin/snakePipes", line 270, in envInfo
    md5hash.update(condaEnvDir.encode())
                   ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'encode'

```version of snakePipes:
```bash
snakePipes version
version 2.8.1
```
My python is version 3.11

**Comment by WardDeb** [comment]
What is the condaEnvDir variable set to in your 'defaults.yaml' file ? (`snakePipes info `to get the path to it).

**Comment by sunta3iouxos** [comment]
interestingly it is 
```bash
null
```

**Comment by WardDeb** [comment]
Was it set before ? If not, fill in an appropriate path (without a trailing slash), and you should be able to continue then.
